
ENERGIA_ENTRENAMIENTO = 5

MIN_AUMENTO_EXPERIENCIA = 10
MAX_AUMENTO_EXPERIENCIA = 60

MIN_AUMENTO_ENTRENAMIENTO = 10
MAX_AUMENTO_ENTRENAMIENTO = 50

AUMENTAR_VIDA_PLANTA = 20
AUMENTAR_ATAQUE_FUEGO = 15
AUMENTAR_VELOCIDAD_AGUA = 12



#Baya
GASTO_ENERGIA_BAYA = 5
PROB_EXITO_BAYA = 0.7

#Pocion
GASTO_ENERGIA_POCION = 3
PROB_EXITO_POCION = 0.5

#Caramelo
GASTO_ENERGIA_CARAMELO = 7
PROB_EXITO_CARAMELO = 0.3

AUMENTO_DEFENSA = 5

